services:

  mysql:
    image: mysql:8.4
    container_name: oes-mysql

    environment:
      MYSQL_DATABASE: online_examination_system_2
      MYSQL_ROOT_PASSWORD: RaviMySQL

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: oes-app

    depends_on:
      - mysql

    environment:
      SPRING_PROFILES_ACTIVE: docker

      DB_URL: jdbc:mysql://mysql:3306/online_examination_system_2
      DB_USERNAME: root
      DB_PASSWORD: RaviMySQL

      JWT_SECRET: K8vP2xQ9mL4zR7nT5wY1cH6sJ3dF9aB2eG7kN4pX8qV5rM1tZ

    ports:
      - "8080:8080"

volumes:
  mysql_data: